/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wy_imagendk_ImageNdkUtils */

#ifndef _Included_com_wy_imagendk_ImageNdkUtils
#define _Included_com_wy_imagendk_ImageNdkUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wy_imagendk_ImageNdkUtils
 * Method:    getImage
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_wy_imagendk_ImageNdkUtils_getImage
  (JNIEnv *, jclass, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
